version: '3'
services:
  zookeeper:
    image: zookeeper:3.7.0
    container_name: zookeeper
    restart: "no"
    networks:
      - spring-cloud-network
    ports:
      - "2181:2181"

  kafka:
    image: obsidiandynamics/kafka
    container_name: kafka
    restart: "no"
    networks:
      - spring-cloud-network
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER_INTERNAL:PLAINTEXT,DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: DOCKER_INTERNAL://:29092,DOCKER_EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: DOCKER_INTERNAL://kafka:29092,DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_ID : group_id
      KAFKA_CREATE_TOPICS: "register:1:1 , notify:1:1"
    depends_on:
      - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    restart: "no"
    networks:
      - spring-cloud-network
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
    depends_on:
      - "kafka"

  dispatch-service:
    container_name: dispatch-service
    build:
      context: ./dispatch-service
      dockerfile: Dockerfile
    image: dispatch-service:latest
    ports:
      - 8082:8082
    networks:
      - spring-cloud-network
    depends_on:
      - zookeeper
      - kafka
  register-service:
    container_name: register-service
    build:
      context: ./register-service
      dockerfile: Dockerfile
    image: register-service:latest
    ports:
      - 8081:8081
    networks:
      - spring-cloud-network
    depends_on:
      - zookeeper
      - kafka

  email-service:
    container_name: email-service
    build:
      context: ./email-service
      dockerfile: Dockerfile
    image: email-service:latest
    ports:
      - 8083:8083
    networks:
      - spring-cloud-network
    depends_on:
      - zookeeper
      - kafka

networks:
  spring-cloud-network:
    name: spring-cloud-network
    driver: bridge
