apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service
spec:
  selector:
    matchLabels:
      app: email-service
  template:
    metadata:
      labels:
        app: email-service
    spec:
      containers:
      - name: email-service
        image: kube/email-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9003

---
apiVersion: v1
kind: Service
metadata:
  name: email-service-service
spec:
  type: LoadBalancer
  selector:
    app: email-service
  ports:
  - protocol: TCP
    port: 9003
    targetPort: 9003
